development:
  perform_authentication: false
  username: admin
  password: secret
  access_key_id:
  secret_access_key:
  base_url: http://localhost:3000
  domain: yoursitedomain.com

test:
  perform_authentication: false
  username: admin
  password: secret
  access_key_id:
  secret_access_key:
  base_url: http://localhost:3000
  domain: yoursitedomain.com

production:
  perform_authentication: true
  username: admin
  password: secret
  access_key_id:
  secret_access_key:
  base_url: http://www.yoursubscribersurl.com
  domain: yoursitedomain.com
